const WEB_URL = 'buzzho[.]me';
module.exports = [
  `Bạn cần tìm thuê căn hộ/phòng đúng ý nhanh chóng hay cần tìm khách thì xem thử app này nhe, free hoàn toàn ${WEB_URL}`,
  `Chuẩn bị ra mắt công cụ để tìm khách, căn hộ đúng ý miễn phí. Mn quan tâm thì đăng ký trước để được miễn phí trong đợt COVID-19 này nha ❤️ ${WEB_URL}`,
  `App để tìm khách, căn hộ đúng ý miễn phí, đăng ký trước để được miễn phí ❤️ ${WEB_URL}`,
  `Bạn cần tìm thuê căn hộ/phòng đúng ý nhanh chóng hay cần tìm khách thì xem thử app này. Mn ai quan tâm thì xem thử, chỉ free cho ai đăng ký trong 9 ngày nhe ❤️ ${WEB_URL}`,
  `Bạn cần tìm thuê phòng hoặc tìm khách thuê nhà nhanh, tiết kiệm thời gian thì tìm trên app này thử nhé ❤️ ${WEB_URL}`,
  `Chào bạn, công cụ này giúp bạn tìm thuê phòng hoặc tìm khách thuê nhà nhanh chóng, tiết kiệm thời gian lắm á. Bạn thử xem nhé ❤️ ${WEB_URL}`,
  `Bạn ghé xem thử app ❤️ ${WEB_URL} để tìm thuê phòng hoặc tìm khách thuê nhà nhanh chóng, tiết kiệm thời gian nha ❤️`,
  `Bạn xem thử trên ${WEB_URL} để tìm thuê phòng hoặc tìm khách thuê nhà nhanh, tiết kiệm thời gian nha. Free nhé bạn ❤️`,
  `Chuẩn bị có app này ❤️ ${WEB_URL} để tìm thuê phòng hoặc tìm khách thuê nhà nhanh, tiết kiệm thời gian nhe. Bạn xem thử nhé ❤️`,
  `Tìm nhà, tìm khách thuê nhà nhanh chóng trên ${WEB_URL}, giúp bạn tiết kiệm thời gian và dễ tìm được phòng/ nhà cần thuê đúng ý. Free nhé bạn ❤️`,
  `Bạn thử ghé xem trang này ${WEB_URL} vừa free, vừa dễ tìm phòng/ nhà/ căn hộ cho thuê hoặc tìm khách thuê nhà, vừa tiết kiệm thời gian nha bạn ❤️`,
  `Nếu bạn đang cần tìm thuê căn hộ/phòng/nhà hoặc cần tìm khách thuê nhà nhanh thì xem thử cái này để tiết kiệm thời gian tìm kiếm nha ${WEB_URL}`,
  `Bạn cần thuê phòng hoặc nhà nhanh chóng hay cần tìm khách thuê nhà thì xem thử app này, free nhé bạn ${WEB_URL}`,
  `Ban can thue phong hoac nha nhanh chong hay can tim khach thue nha nhanh thi xem thu app nay ${WEB_URL}. Thanks ban!`,
  `Bạn tìm thuê nhà trên trang này nè, vừa tiết kiệm thời gian, vừa tìm được nhà nhanh chóng nha ❤️ ${WEB_URL} . Cheers.`,
  `Trang này giúp bạn tìm nhà cho thuê hay tìm khách thuê nhà nhanh chóng, hiệu quả nè bạn ${WEB_URL} ❤️`,
  `Sắp có trang này miễn phí, giúp bạn tìm nhà cho thuê hay tìm khách thuê nhà nhanh chóng ${WEB_URL} ❤️. Bạn thử xem nhe`,
  `Bạn xem thử trang này ${WEB_URL} để tìm nhà/ phòng/ căn hộ cho thuê nhanh chóng hoặc tìm khách thuê nhà. Đăng ký sớm để được free nhé ❤️`,
  `Trang này ${WEB_URL} vừa tiết kiệm thời gian, vừa tìm nhà nhanh chóng. Dành cho những bạn muốn tìm nhà/ phòng/ căn hộ cho thuê hoặc tìm khách thuê nhà nhanh chóng, hiệu quả. Bạn xem thử nhe ❤️`,
];
