module.exports = [
    "Airbnb Hosts in Saigon (HCMC) - Vietnam",
    "Apartment for rent in Ho Chi Minh City - Saigon Housing",
    "Housing for expats in Ho Chi Minh City ( Saigon)",
    "Housing Ho Chi Minh City (Saigon)",
    "District 7 - Apartment for rent in Ho Chi Minh City (Expat Housing)",
    "Airbnb Hosts in Saigon - Ho Chi Minh City - Vietnam",
    "Apartments for Rent In Ho Chi Minh",
    "Saigon Expat - Airbnb - Homestay - Apartment",
    "Airbnb Hosts in Saigon (Ho Chi Minh City)",
    "Bất Động Sản TP Hồ Chí Minh Group - Hội BĐS HCM ☑",
    "Rooms, flats, apartments & houses for rent - Ho Chi Minh City - Vietnam",
    "Apartment for rent in Ho Chi Minh City",
    "CHO THUÊ CĂN HỘ CHUNG CƯ SÀI GÒN",
    "Chung cư mini cho thuê/căn hộ dịch vụ- SinvaHome HCM (Q1,Q3,Q7,Q8,Q10,..)",
    "Công Đồng Homestay + Hostel ở Sài Gòn",
    "HOUSING IN SAIGON (HO CHI MINH CITY, VIETNAM)",
    "Housing/Apartments for rent in Saigon - Vietnam",
    "APARTMENT HOUSE FOR RENT LEASE IN HCMC",
    "Binh Thanh - Apartment for rent in Ho Chi Minh City (Expat Housing)",
    "HOUSING SOLUTIONS FOR EXPATS & LOCALS IN HO CHI MINH CITY (SAIGON) -VIETNAM",
    "CHO THUÊ PHÒNG - CĂN HỘ DỊCH VỤ- VĂN PHÒNG TẠI TPHCM",
    "Housing & Apartment For Rent In Ho Chi Minh City (Saigon) - Vietnam",
    "Expats in Ho Chi Minh City (Saigon) Vietnam",
    "Tìm & Cho thuê Phòng trọ- Nhà nguyên căn (CC) giá bình dân TP Hồ Chí Minh",
    "Phòng Trọ TPHCM"
]